"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
************ SAFETY WARNING *******************************
When developing a new script, always test without a propeller
installed. Only install the propeller on the motor. When you
are confident the script has no bugs and works as intended.

Always follow the user guide provided with the product.
***********************************************************

The package name should start with the company name and end with the major version.
"""

import abc
import collections.abc
import flight_stand_api_v1_pb2
import google.protobuf.empty_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class FlightStandStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetServerStatus: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetServerStatusRequest,
        flight_stand_api_v1_pb2.ServerStatus,
    ]
    """Returns the server status. Poll this function from the client regularly. If this function is not called at least
    once per second, the core will trigger a cutoff. Calling this function every 1/2 second will work. Only one client
    is required to perform this poll. If the GUI is running, the user script does not have to regularly call this rpc.
    """

    GetCore: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Returns the core information"""

    UpdateCore: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Make changes to the core"""

    WatchCore: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Watches any changes on the core. When first called, the current Core is returned."""

    ListCutoffConditions: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListCutoffConditionsRequest,
        flight_stand_api_v1_pb2.ListCutoffConditionsResponse,
    ]
    """Lists cutoff conditions that prevent the cutoff from being reset."""

    TriggerCutoff: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TriggerCutoffRequest,
        flight_stand_api_v1_pb2.TriggerCutoffResponse,
    ]
    """Triggers a manual safety cutoff."""

    ClearCutoff: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearCutoffRequest,
        flight_stand_api_v1_pb2.ClearCutoffResponse,
    ]
    """Clears a safety cutoff. Although no error will be returned, this will only work if there are no active cutoff
    conditions. It is possible a signal becomes out-of-range immediately after reset, triggering a new cutoff
    immediately after.
    """

    SyncTimestamps: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.SyncTimestampsRequest,
        flight_stand_api_v1_pb2.SyncTimestampsResponse,
    ]
    """Triggers a manual timestamp sync. This helps with debugging."""

    GetBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetBoardRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Gets a board"""

    ListBoards: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBoardsRequest,
        flight_stand_api_v1_pb2.ListBoardsResponse,
    ]
    """Lists available boards (those that successfully connected and identified)"""

    WatchBoards: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchBoardsRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Watch boards. When first called, each board is streamed once."""

    ConnectBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ConnectBoardRequest,
        flight_stand_api_v1_pb2.ConnectBoardResponse,
    ]
    """Manually connect a board. Needed when autoconnect is disabled in the core settings."""

    ResetBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ResetBoardRequest,
        flight_stand_api_v1_pb2.ResetBoardResponse,
    ]
    """Resets a board. The core will automatically attempt to reconnect after the reset. This RPC may take a few seconds
    depending on the hardware implementation.
    """

    IdentifyBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.IdentifyBoardRequest,
        flight_stand_api_v1_pb2.IdentifyBoardResponse,
    ]
    """Identify a board will flash the light of the board in red, green, blue and white for a couple seconds."""

    CorruptBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CorruptBoardRequest,
        flight_stand_api_v1_pb2.CorruptBoardResponse,
    ]
    """For development and testing purposes only. Corrupts communication data on purpose to test recovery mechanisms."""

    DisconnectBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DisconnectBoardRequest,
        flight_stand_api_v1_pb2.DisconnectBoardResponse,
    ]
    """Manually disconnect a board. Closes the board connection and releases resources (eg. COM port)."""

    CreateSimulatedBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateSimulatedBoardRequest,
        flight_stand_api_v1_pb2.CreateSimulatedBoardResponse,
    ]
    """Add a simulated boards with virtual hardware. At this time, the simulated board cannot be customized. It simulates
    a small motor/propeller setup generating near 200 grams of thrust at full throttle.
    """

    GetSimulatedBoardSettings: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetSimulatedBoardSettingsRequest,
        flight_stand_api_v1_pb2.SimulatedBoardSettings,
    ]
    """Simulated boards can have some of its simulated properties changed after they have been created. For example, the
    user can add simulated correction weights to offset the simulated rotor unbalance.
    """

    UpdateSimulatedBoardSettings: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsRequest,
        flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsResponse,
    ]

    CreateExternalBoard: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateExternalBoardRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Note: this feature requires a free license key. Contact support@tytorobotics.com to obtain one.
    Add an external board that fully interacts with the Flight Stand Software. This enables the user to interface
    external inputs and outputs, essentially allowing the control of CANbus ESCs and to add custom sensors and outputs.
    Once an external board is created, use the WriteExternalSamples rpc to update external sensor data, and use the
    WatchOutputs rpc to react to changes on the output targets. When reacting to changes on the output targets, you
    must take into account the rate limiter imposed by the user, Provide feedback the output reacted through the
    WriteExternalSamples rpc. See examples in the Python documentation for more information.
    """

    FlashBoardFirmware: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.FlashBoardFirmwareRequest,
        flight_stand_api_v1_pb2.FlashBoardFirmwareResponse,
    ]
    """Flashes the firmware on a board. The core has the correct supported firmware in its source already. The core will
    handle all the logic to reset, disconnect, flash, reconnect, etc...
    """

    GetInput: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetInputRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Gets an input"""

    UpdateInput: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateInputRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Updates an input"""

    ListInputs: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListInputsRequest,
        flight_stand_api_v1_pb2.ListInputsResponse,
    ]
    """Lists available inputs. Does not return closed inputs"""

    WatchInputs: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchInputsRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Watches inputs for changes (other than the values). When first called, each available input is streamed once."""

    TareInputs: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TareInputsRequest,
        flight_stand_api_v1_pb2.TareInputsResponse,
    ]
    """Tares all inputs on all boards that can be tared, for example load cells."""

    ListSamples: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSamplesRequest,
        flight_stand_api_v1_pb2.ListSamplesResponse,
    ]
    """Returns the latest Sample values."""

    WatchSamples: grpc.StreamStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchSamplesRequest,
        flight_stand_api_v1_pb2.WatchSamplesResponse,
    ]
    """Regularly get Sample updates. This RPC is designed to provide real-time updates for the Flight Stand GUI's plots.
    Unlike polling with ListSamples, this method uses an internal buffer that accumulates updates (up to a reasonable
    limit) when the client temporarily slows down, ensuring that the client won't miss any updates. This is especially
    useful when the GUI freezes occasionally due to actions like docking or undocking windows. The network stream is
    also buffered, and a response is sent only when a request is received to prevent lag. It's important to note that
    this RPC has been heavily optimized for use with the Flight Stand GUI. The sample rate is fixed at 10 Hz and
    cannot be configured. The RPC has been crafted and optimized to provide smooth real-time plots in the GUI while
    keeping RAM and CPU usage within reasonable limits. To prevent the send buffer from filling up, the RPC employs
    techniques similar to those used in real-time video conferencing. The idea is to limit latency by limiting the
    amount of buffering that can be done. To achieve this, the client must acknowledge receipt of the data before the
    RPC will send more data. In summary, it's required to use this RPC as a bidirectional stream, as it expects the GUI
    to respond after each update.
    """

    WriteExternalSamples: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.WriteExternalSamplesRequest,
        flight_stand_api_v1_pb2.WriteExternalSamplesResponse,
    ]
    """Writes external input samples. This rpc only works on external inputs added using the CreateExternalBoard rpc.
    When creating the Sample, assign the input's raw_signal_name field to the Sample's signal_name field.
    """

    GetSignal: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetSignalRequest,
        flight_stand_api_v1_pb2.Signal,
    ]
    """Gets a signal. See the "Signal" message for more information about what a signal represents."""

    ListSignals: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSignalsRequest,
        flight_stand_api_v1_pb2.ListSignalsResponse,
    ]
    """List all signals."""

    WatchSignals: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchSignalsRequest,
        flight_stand_api_v1_pb2.Signal,
    ]
    """Watch signals for changes. When first called, all signals are streamed once."""

    ListSignalStats: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSignalStatsRequest,
        flight_stand_api_v1_pb2.ListSignalStatsResponse,
    ]
    """List signal stats. ♦s signal performance metrics, like update rate."""

    GetOutput: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetOutputRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Get an output's configuration (cutoff, range, alias, protocol, etc...)."""

    UpdateOutput: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateOutputRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Update an output's configuration or target value."""

    ListOutputs: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListOutputsRequest,
        flight_stand_api_v1_pb2.ListOutputsResponse,
    ]
    """List all outputs. Does not return closed outputs."""

    WatchOutputs: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchOutputsRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Watch outputs for changes of configuration, other than OutputSignal changes."""

    UpdateTimedActionSequence: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTimedActionSequenceRequest,
        flight_stand_api_v1_pb2.TimedActionSequence,
    ]
    """Updates the action sequence (appends to previous sequence). This feature is related to automatic control. It allows
    controlling outputs in real-time at up to 1000 hz by specifying the update time. Compared to updating outputs
    directly using the UpdateOutput method, this method avoids issues with network/USB communication latency and
    limited rate of updates. Using this method ensures the outputs are updated at the correct time within the hardware.
    """

    ClearTimedActionSequence: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearTimedActionSequenceRequest,
        flight_stand_api_v1_pb2.ClearTimedActionSequenceResponse,
    ]
    """Clears the action sequence across all devices. This will prevent future updates from happening."""

    GetPowertrain: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetPowertrainRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Gets a powertrain. A powertrain represents a combination of a motor, a propeller, and an ESC. Each powertrain
    should be mapped with corresponding hardware sensors and outputs. The core will automatically calculate derived
    signals when possible. For example, if both a current and a voltage sensors are mapped, an "electrical power" is
    derived signal is generated.
    """

    UpdatePowertrain: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdatePowertrainRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Updates a powertrain."""

    ListPowertrains: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListPowertrainsRequest,
        flight_stand_api_v1_pb2.ListPowertrainsResponse,
    ]
    """Lists all powertrains."""

    ClearPowertrain: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearPowertrainRequest,
        flight_stand_api_v1_pb2.ClearPowertrainResponse,
    ]
    """Clear a powertrain (removes every mapping and component names)."""

    WatchPowertrains: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchPowertrainsRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Watch changes on powertrains."""

    GetTestRecorder: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Gets the test recorder, used to prepare a test before saving."""

    UpdateTestRecorder: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Updates the test recorder."""

    WatchTestRecorder: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Watch the test recorder for changes."""

    TakeSampleTestRecorder: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TakeSampleTestRecorderRequest,
        flight_stand_api_v1_pb2.TakeSampleTestRecorderResponse,
    ]
    """Take a data sample."""

    ClearTestRecorder: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearTestRecorderRequest,
        flight_stand_api_v1_pb2.ClearTestRecorderResponse,
    ]
    """Discard changes and start a new test recorder."""

    SaveTestRecorder: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.SaveTestRecorderRequest,
        flight_stand_api_v1_pb2.SaveTestRecorderResponse,
    ]
    """Save the test recorder as a new Test."""

    GetTest: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetTestRequest,
        flight_stand_api_v1_pb2.Test,
    ]
    """Gets a Test."""

    UpdateTest: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTestRequest,
        flight_stand_api_v1_pb2.Test,
    ]
    """Update a Test."""

    ListTests: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListTestsRequest,
        flight_stand_api_v1_pb2.ListTestsResponse,
    ]
    """List all tests."""

    DeleteTest: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DeleteTestRequest,
        google.protobuf.empty_pb2.Empty,
    ]
    """Delete a test."""

    ListTestData: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListTestSamplesRequest,
        flight_stand_api_v1_pb2.ListTestSamplesResponse,
    ]
    """Retrieve the recorded data for a test (may be interpolated to reduce the amount of data). The data is returned with
    timestamps in order. The deadline specified in the context of the API call will force an early return even if the
    length of the returned data has not reached pageSize. This is useful to display progress bars.
    """

    DevListBoardParameters: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevListBoardParametersRequest,
        flight_stand_api_v1_pb2.DevListBoardParametersResponse,
    ]
    """Lists all board parameters. This function is synchronous, and will return after fetching all board parameters from
    the board. Important: for dev purposes ONLY (it bypasses all safety and business logic). Calling this function may
    also have unexpected behavior (may trigger an internal cutoff, stop data streaming, or load default values).
    """

    DevUpdateBoardParameter: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevUpdateBoardParameterRequest,
        flight_stand_api_v1_pb2.BoardParameter,
    ]
    """Updates a board parameter. For simplicity this update method does not use field masks, so the whole parameter
    must be specified when updating. For dev purposes ONLY (it bypasses all safety and business logic). There is no
    defined behavior on the effect of updating a parameter (changes are not expected to propagate, a board reset may be
    needed for changes to take effect).
    """

    DevClearBoardParameters: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevClearBoardParametersRequest,
        flight_stand_api_v1_pb2.DevClearBoardParametersResponse,
    ]
    """Clears all parameters to 0 value. It is recommended to leave a timeout of 30 seconds for this command to reply.
    For dev purposes ONLY. This will delete all calibration data, and the circuit will become unusable.
    """

    ListInputTransformations: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListInputTransformationsRequest,
        flight_stand_api_v1_pb2.ListInputTransformationsResponse,
    ]
    """List existing InputTransformations"""

    UpdateInputTransformations: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateInputTransformationsRequest,
        flight_stand_api_v1_pb2.UpdateInputTransformationsResponse,
    ]
    """Updates the list of input transformations. The order of the transformations is important when chaining them."""

    WatchInputTransformations: grpc.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchInputTransformationsRequest,
        flight_stand_api_v1_pb2.WatchInputTransformationsResponse,
    ]
    """Watch input transformations. When first called, it sends the current list of input transformations. Each time there
    is an update, all inputs transformations are resent because their order is important.
    """

    LoadTransformationFromID: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.LoadTransformationFromIDRequest,
        flight_stand_api_v1_pb2.LoadTransformationFromIDResponse,
    ]
    """Load Tyto Robotics transformation. For sensors sold and calibrated by Tyto Robotics, the transformation associated
    with the sensor can be loaded by entering the calibration ID found in the product's label. It will show as a new
    transformation.
    """

    ListBalancingSessions: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBalancingSessionsRequest,
        flight_stand_api_v1_pb2.ListBalancingSessionsResponse,
    ]
    """Lists available balancing sessions."""

    DeleteBalancingSession: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DeleteBalancingSessionRequest,
        google.protobuf.empty_pb2.Empty,
    ]
    """Delete a balance session."""

    CreateBalancingSession: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateBalancingSessionRequest,
        flight_stand_api_v1_pb2.CreateBalancingSessionResponse,
    ]
    """Creates a new balancing session. The new session can only be modified if the system state matches the system's
    snapshot state when the session is created and if the session is the last in the list of sessions.
    """

    ExecuteBalancingRun: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ExecuteBalancingRunRequest,
        flight_stand_api_v1_pb2.ExecuteBalancingRunResponse,
    ]
    """Synchronous function that captures and analyzes a run of data and appends it to the last balancing session.
    Add trial or correction weight. By definition a trial weight is the first weight added for the trial run, while
    correction weights are applied to correct the balance in one or more correction runs.
    The first run is done without any correction weight, and is called the initial run.
    The second run has a trial weight and is called a trial run. This is where Wa and WT are determined.
    Subsequent runs are called correction runs and there can be one or more.
    """

    ListBalanceRunData: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBalanceRunDataRequest,
        flight_stand_api_v1_pb2.ListBalanceRunDataResponse,
    ]
    """Retrieves the recorded data points for a balancing run"""

    GetOhmValue: grpc.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetOhmValueRequest,
        flight_stand_api_v1_pb2.GetOhmValueResponse,
    ]
    """Gets ohmic resistance of the motor windings."""

class FlightStandAsyncStub:
    GetServerStatus: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetServerStatusRequest,
        flight_stand_api_v1_pb2.ServerStatus,
    ]
    """Returns the server status. Poll this function from the client regularly. If this function is not called at least
    once per second, the core will trigger a cutoff. Calling this function every 1/2 second will work. Only one client
    is required to perform this poll. If the GUI is running, the user script does not have to regularly call this rpc.
    """

    GetCore: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Returns the core information"""

    UpdateCore: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Make changes to the core"""

    WatchCore: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchCoreRequest,
        flight_stand_api_v1_pb2.Core,
    ]
    """Watches any changes on the core. When first called, the current Core is returned."""

    ListCutoffConditions: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListCutoffConditionsRequest,
        flight_stand_api_v1_pb2.ListCutoffConditionsResponse,
    ]
    """Lists cutoff conditions that prevent the cutoff from being reset."""

    TriggerCutoff: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TriggerCutoffRequest,
        flight_stand_api_v1_pb2.TriggerCutoffResponse,
    ]
    """Triggers a manual safety cutoff."""

    ClearCutoff: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearCutoffRequest,
        flight_stand_api_v1_pb2.ClearCutoffResponse,
    ]
    """Clears a safety cutoff. Although no error will be returned, this will only work if there are no active cutoff
    conditions. It is possible a signal becomes out-of-range immediately after reset, triggering a new cutoff
    immediately after.
    """

    SyncTimestamps: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.SyncTimestampsRequest,
        flight_stand_api_v1_pb2.SyncTimestampsResponse,
    ]
    """Triggers a manual timestamp sync. This helps with debugging."""

    GetBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetBoardRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Gets a board"""

    ListBoards: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBoardsRequest,
        flight_stand_api_v1_pb2.ListBoardsResponse,
    ]
    """Lists available boards (those that successfully connected and identified)"""

    WatchBoards: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchBoardsRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Watch boards. When first called, each board is streamed once."""

    ConnectBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ConnectBoardRequest,
        flight_stand_api_v1_pb2.ConnectBoardResponse,
    ]
    """Manually connect a board. Needed when autoconnect is disabled in the core settings."""

    ResetBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ResetBoardRequest,
        flight_stand_api_v1_pb2.ResetBoardResponse,
    ]
    """Resets a board. The core will automatically attempt to reconnect after the reset. This RPC may take a few seconds
    depending on the hardware implementation.
    """

    IdentifyBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.IdentifyBoardRequest,
        flight_stand_api_v1_pb2.IdentifyBoardResponse,
    ]
    """Identify a board will flash the light of the board in red, green, blue and white for a couple seconds."""

    CorruptBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CorruptBoardRequest,
        flight_stand_api_v1_pb2.CorruptBoardResponse,
    ]
    """For development and testing purposes only. Corrupts communication data on purpose to test recovery mechanisms."""

    DisconnectBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DisconnectBoardRequest,
        flight_stand_api_v1_pb2.DisconnectBoardResponse,
    ]
    """Manually disconnect a board. Closes the board connection and releases resources (eg. COM port)."""

    CreateSimulatedBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateSimulatedBoardRequest,
        flight_stand_api_v1_pb2.CreateSimulatedBoardResponse,
    ]
    """Add a simulated boards with virtual hardware. At this time, the simulated board cannot be customized. It simulates
    a small motor/propeller setup generating near 200 grams of thrust at full throttle.
    """

    GetSimulatedBoardSettings: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetSimulatedBoardSettingsRequest,
        flight_stand_api_v1_pb2.SimulatedBoardSettings,
    ]
    """Simulated boards can have some of its simulated properties changed after they have been created. For example, the
    user can add simulated correction weights to offset the simulated rotor unbalance.
    """

    UpdateSimulatedBoardSettings: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsRequest,
        flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsResponse,
    ]

    CreateExternalBoard: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateExternalBoardRequest,
        flight_stand_api_v1_pb2.Board,
    ]
    """Note: this feature requires a free license key. Contact support@tytorobotics.com to obtain one.
    Add an external board that fully interacts with the Flight Stand Software. This enables the user to interface
    external inputs and outputs, essentially allowing the control of CANbus ESCs and to add custom sensors and outputs.
    Once an external board is created, use the WriteExternalSamples rpc to update external sensor data, and use the
    WatchOutputs rpc to react to changes on the output targets. When reacting to changes on the output targets, you
    must take into account the rate limiter imposed by the user, Provide feedback the output reacted through the
    WriteExternalSamples rpc. See examples in the Python documentation for more information.
    """

    FlashBoardFirmware: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.FlashBoardFirmwareRequest,
        flight_stand_api_v1_pb2.FlashBoardFirmwareResponse,
    ]
    """Flashes the firmware on a board. The core has the correct supported firmware in its source already. The core will
    handle all the logic to reset, disconnect, flash, reconnect, etc...
    """

    GetInput: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetInputRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Gets an input"""

    UpdateInput: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateInputRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Updates an input"""

    ListInputs: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListInputsRequest,
        flight_stand_api_v1_pb2.ListInputsResponse,
    ]
    """Lists available inputs. Does not return closed inputs"""

    WatchInputs: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchInputsRequest,
        flight_stand_api_v1_pb2.Input,
    ]
    """Watches inputs for changes (other than the values). When first called, each available input is streamed once."""

    TareInputs: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TareInputsRequest,
        flight_stand_api_v1_pb2.TareInputsResponse,
    ]
    """Tares all inputs on all boards that can be tared, for example load cells."""

    ListSamples: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSamplesRequest,
        flight_stand_api_v1_pb2.ListSamplesResponse,
    ]
    """Returns the latest Sample values."""

    WatchSamples: grpc.aio.StreamStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchSamplesRequest,
        flight_stand_api_v1_pb2.WatchSamplesResponse,
    ]
    """Regularly get Sample updates. This RPC is designed to provide real-time updates for the Flight Stand GUI's plots.
    Unlike polling with ListSamples, this method uses an internal buffer that accumulates updates (up to a reasonable
    limit) when the client temporarily slows down, ensuring that the client won't miss any updates. This is especially
    useful when the GUI freezes occasionally due to actions like docking or undocking windows. The network stream is
    also buffered, and a response is sent only when a request is received to prevent lag. It's important to note that
    this RPC has been heavily optimized for use with the Flight Stand GUI. The sample rate is fixed at 10 Hz and
    cannot be configured. The RPC has been crafted and optimized to provide smooth real-time plots in the GUI while
    keeping RAM and CPU usage within reasonable limits. To prevent the send buffer from filling up, the RPC employs
    techniques similar to those used in real-time video conferencing. The idea is to limit latency by limiting the
    amount of buffering that can be done. To achieve this, the client must acknowledge receipt of the data before the
    RPC will send more data. In summary, it's required to use this RPC as a bidirectional stream, as it expects the GUI
    to respond after each update.
    """

    WriteExternalSamples: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.WriteExternalSamplesRequest,
        flight_stand_api_v1_pb2.WriteExternalSamplesResponse,
    ]
    """Writes external input samples. This rpc only works on external inputs added using the CreateExternalBoard rpc.
    When creating the Sample, assign the input's raw_signal_name field to the Sample's signal_name field.
    """

    GetSignal: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetSignalRequest,
        flight_stand_api_v1_pb2.Signal,
    ]
    """Gets a signal. See the "Signal" message for more information about what a signal represents."""

    ListSignals: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSignalsRequest,
        flight_stand_api_v1_pb2.ListSignalsResponse,
    ]
    """List all signals."""

    WatchSignals: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchSignalsRequest,
        flight_stand_api_v1_pb2.Signal,
    ]
    """Watch signals for changes. When first called, all signals are streamed once."""

    ListSignalStats: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListSignalStatsRequest,
        flight_stand_api_v1_pb2.ListSignalStatsResponse,
    ]
    """List signal stats. Gets signal performance metrics, like update rate."""

    GetOutput: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetOutputRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Get an output's configuration (cutoff, range, alias, protocol, etc...)."""

    UpdateOutput: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateOutputRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Update an output's configuration or target value."""

    ListOutputs: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListOutputsRequest,
        flight_stand_api_v1_pb2.ListOutputsResponse,
    ]
    """List all outputs. Does not return closed outputs."""

    WatchOutputs: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchOutputsRequest,
        flight_stand_api_v1_pb2.Output,
    ]
    """Watch outputs for changes of configuration, other than OutputSignal changes."""

    UpdateTimedActionSequence: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTimedActionSequenceRequest,
        flight_stand_api_v1_pb2.TimedActionSequence,
    ]
    """Updates the action sequence (appends to previous sequence). This feature is related to automatic control. It allows
    controlling outputs in real-time at up to 1000 hz by specifying the update time. Compared to updating outputs
    directly using the UpdateOutput method, this method avoids issues with network/USB communication latency and
    limited rate of updates. Using this method ensures the outputs are updated at the correct time within the hardware.
    """

    ClearTimedActionSequence: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearTimedActionSequenceRequest,
        flight_stand_api_v1_pb2.ClearTimedActionSequenceResponse,
    ]
    """Clears the action sequence across all devices. This will prevent future updates from happening."""

    GetPowertrain: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetPowertrainRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Gets a powertrain. A powertrain represents a combination of a motor, a propeller, and an ESC. Each powertrain
    should be mapped with corresponding hardware sensors and outputs. The core will automatically calculate derived
    signals when possible. For example, if both a current and a voltage sensors are mapped, an "electrical power" is
    derived signal is generated.
    """

    UpdatePowertrain: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdatePowertrainRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Updates a powertrain."""

    ListPowertrains: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListPowertrainsRequest,
        flight_stand_api_v1_pb2.ListPowertrainsResponse,
    ]
    """Lists all powertrains."""

    ClearPowertrain: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearPowertrainRequest,
        flight_stand_api_v1_pb2.ClearPowertrainResponse,
    ]
    """Clear a powertrain (removes every mapping and component names)."""

    WatchPowertrains: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchPowertrainsRequest,
        flight_stand_api_v1_pb2.Powertrain,
    ]
    """Watch changes on powertrains."""

    GetTestRecorder: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Gets the test recorder, used to prepare a test before saving."""

    UpdateTestRecorder: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Updates the test recorder."""

    WatchTestRecorder: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchTestRecorderRequest,
        flight_stand_api_v1_pb2.TestRecorder,
    ]
    """Watch the test recorder for changes."""

    TakeSampleTestRecorder: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.TakeSampleTestRecorderRequest,
        flight_stand_api_v1_pb2.TakeSampleTestRecorderResponse,
    ]
    """Take a data sample."""

    ClearTestRecorder: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ClearTestRecorderRequest,
        flight_stand_api_v1_pb2.ClearTestRecorderResponse,
    ]
    """Discard changes and start a new test recorder."""

    SaveTestRecorder: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.SaveTestRecorderRequest,
        flight_stand_api_v1_pb2.SaveTestRecorderResponse,
    ]
    """Save the test recorder as a new Test."""

    GetTest: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetTestRequest,
        flight_stand_api_v1_pb2.Test,
    ]
    """Gets a Test."""

    UpdateTest: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateTestRequest,
        flight_stand_api_v1_pb2.Test,
    ]
    """Update a Test."""

    ListTests: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListTestsRequest,
        flight_stand_api_v1_pb2.ListTestsResponse,
    ]
    """List all tests."""

    DeleteTest: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DeleteTestRequest,
        google.protobuf.empty_pb2.Empty,
    ]
    """Delete a test."""

    ListTestData: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListTestSamplesRequest,
        flight_stand_api_v1_pb2.ListTestSamplesResponse,
    ]
    """Retrieve the recorded data for a test (may be interpolated to reduce the amount of data). The data is returned with
    timestamps in order. The deadline specified in the context of the API call will force an early return even if the
    length of the returned data has not reached pageSize. This is useful to display progress bars.
    """

    DevListBoardParameters: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevListBoardParametersRequest,
        flight_stand_api_v1_pb2.DevListBoardParametersResponse,
    ]
    """Lists all board parameters. This function is synchronous, and will return after fetching all board parameters from
    the board. Important: for dev purposes ONLY (it bypasses all safety and business logic). Calling this function may
    also have unexpected behavior (may trigger an internal cutoff, stop data streaming, or load default values).
    """

    DevUpdateBoardParameter: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevUpdateBoardParameterRequest,
        flight_stand_api_v1_pb2.BoardParameter,
    ]
    """Updates a board parameter. For simplicity this update method does not use field masks, so the whole parameter
    must be specified when updating. For dev purposes ONLY (it bypasses all safety and business logic). There is no
    defined behavior on the effect of updating a parameter (changes are not expected to propagate, a board reset may be
    needed for changes to take effect).
    """

    DevClearBoardParameters: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DevClearBoardParametersRequest,
        flight_stand_api_v1_pb2.DevClearBoardParametersResponse,
    ]
    """Clears all parameters to 0 value. It is recommended to leave a timeout of 30 seconds for this command to reply.
    For dev purposes ONLY. This will delete all calibration data, and the circuit will become unusable.
    """

    ListInputTransformations: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListInputTransformationsRequest,
        flight_stand_api_v1_pb2.ListInputTransformationsResponse,
    ]
    """List existing InputTransformations"""

    UpdateInputTransformations: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.UpdateInputTransformationsRequest,
        flight_stand_api_v1_pb2.UpdateInputTransformationsResponse,
    ]
    """Updates the list of input transformations. The order of the transformations is important when chaining them."""

    WatchInputTransformations: grpc.aio.UnaryStreamMultiCallable[
        flight_stand_api_v1_pb2.WatchInputTransformationsRequest,
        flight_stand_api_v1_pb2.WatchInputTransformationsResponse,
    ]
    """Watch input transformations. When first called, it sends the current list of input transformations. Each time there
    is an update, all inputs transformations are resent because their order is important.
    """

    LoadTransformationFromID: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.LoadTransformationFromIDRequest,
        flight_stand_api_v1_pb2.LoadTransformationFromIDResponse,
    ]
    """Load Tyto Robotics transformation. For sensors sold and calibrated by Tyto Robotics, the transformation associated
    with the sensor can be loaded by entering the calibration ID found in the product's label. It will show as a new
    transformation.
    """

    ListBalancingSessions: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBalancingSessionsRequest,
        flight_stand_api_v1_pb2.ListBalancingSessionsResponse,
    ]
    """Lists available balancing sessions."""

    DeleteBalancingSession: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.DeleteBalancingSessionRequest,
        google.protobuf.empty_pb2.Empty,
    ]
    """Delete a balance session."""

    CreateBalancingSession: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.CreateBalancingSessionRequest,
        flight_stand_api_v1_pb2.CreateBalancingSessionResponse,
    ]
    """Creates a new balancing session. The new session can only be modified if the system state matches the system's
    snapshot state when the session is created and if the session is the last in the list of sessions.
    """

    ExecuteBalancingRun: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ExecuteBalancingRunRequest,
        flight_stand_api_v1_pb2.ExecuteBalancingRunResponse,
    ]
    """Synchronous function that captures and analyzes a run of data and appends it to the last balancing session.
    Add trial or correction weight. By definition a trial weight is the first weight added for the trial run, while
    correction weights are applied to correct the balance in one or more correction runs.
    The first run is done without any correction weight, and is called the initial run.
    The second run has a trial weight and is called a trial run. This is where Wa and WT are determined.
    Subsequent runs are called correction runs and there can be one or more.
    """

    ListBalanceRunData: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.ListBalanceRunDataRequest,
        flight_stand_api_v1_pb2.ListBalanceRunDataResponse,
    ]
    """Retrieves the recorded data points for a balancing run"""

    GetOhmValue: grpc.aio.UnaryUnaryMultiCallable[
        flight_stand_api_v1_pb2.GetOhmValueRequest,
        flight_stand_api_v1_pb2.GetOhmValueResponse,
    ]
    """Gets ohmic resistance of the motor windings."""

class FlightStandServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetServerStatus(
        self,
        request: flight_stand_api_v1_pb2.GetServerStatusRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ServerStatus, collections.abc.Awaitable[flight_stand_api_v1_pb2.ServerStatus]]:
        """Returns the server status. Poll this function from the client regularly. If this function is not called at least
        once per second, the core will trigger a cutoff. Calling this function every 1/2 second will work. Only one client
        is required to perform this poll. If the GUI is running, the user script does not have to regularly call this rpc.
        """

    @abc.abstractmethod
    def GetCore(
        self,
        request: flight_stand_api_v1_pb2.GetCoreRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Core, collections.abc.Awaitable[flight_stand_api_v1_pb2.Core]]:
        """Returns the core information"""

    @abc.abstractmethod
    def UpdateCore(
        self,
        request: flight_stand_api_v1_pb2.UpdateCoreRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Core, collections.abc.Awaitable[flight_stand_api_v1_pb2.Core]]:
        """Make changes to the core"""

    @abc.abstractmethod
    def WatchCore(
        self,
        request: flight_stand_api_v1_pb2.WatchCoreRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Core], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Core]]:
        """Watches any changes on the core. When first called, the current Core is returned."""

    @abc.abstractmethod
    def ListCutoffConditions(
        self,
        request: flight_stand_api_v1_pb2.ListCutoffConditionsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListCutoffConditionsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListCutoffConditionsResponse]]:
        """Lists cutoff conditions that prevent the cutoff from being reset."""

    @abc.abstractmethod
    def TriggerCutoff(
        self,
        request: flight_stand_api_v1_pb2.TriggerCutoffRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TriggerCutoffResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.TriggerCutoffResponse]]:
        """Triggers a manual safety cutoff."""

    @abc.abstractmethod
    def ClearCutoff(
        self,
        request: flight_stand_api_v1_pb2.ClearCutoffRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ClearCutoffResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ClearCutoffResponse]]:
        """Clears a safety cutoff. Although no error will be returned, this will only work if there are no active cutoff
        conditions. It is possible a signal becomes out-of-range immediately after reset, triggering a new cutoff
        immediately after.
        """

    @abc.abstractmethod
    def SyncTimestamps(
        self,
        request: flight_stand_api_v1_pb2.SyncTimestampsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.SyncTimestampsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.SyncTimestampsResponse]]:
        """Triggers a manual timestamp sync. This helps with debugging."""

    @abc.abstractmethod
    def GetBoard(
        self,
        request: flight_stand_api_v1_pb2.GetBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Board, collections.abc.Awaitable[flight_stand_api_v1_pb2.Board]]:
        """Gets a board"""

    @abc.abstractmethod
    def ListBoards(
        self,
        request: flight_stand_api_v1_pb2.ListBoardsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListBoardsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListBoardsResponse]]:
        """Lists available boards (those that successfully connected and identified)"""

    @abc.abstractmethod
    def WatchBoards(
        self,
        request: flight_stand_api_v1_pb2.WatchBoardsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Board], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Board]]:
        """Watch boards. When first called, each board is streamed once."""

    @abc.abstractmethod
    def ConnectBoard(
        self,
        request: flight_stand_api_v1_pb2.ConnectBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ConnectBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ConnectBoardResponse]]:
        """Manually connect a board. Needed when autoconnect is disabled in the core settings."""

    @abc.abstractmethod
    def ResetBoard(
        self,
        request: flight_stand_api_v1_pb2.ResetBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ResetBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ResetBoardResponse]]:
        """Resets a board. The core will automatically attempt to reconnect after the reset. This RPC may take a few seconds
        depending on the hardware implementation.
        """

    @abc.abstractmethod
    def IdentifyBoard(
        self,
        request: flight_stand_api_v1_pb2.IdentifyBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.IdentifyBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.IdentifyBoardResponse]]:
        """Identify a board will flash the light of the board in red, green, blue and white for a couple seconds."""

    @abc.abstractmethod
    def CorruptBoard(
        self,
        request: flight_stand_api_v1_pb2.CorruptBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.CorruptBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.CorruptBoardResponse]]:
        """For development and testing purposes only. Corrupts communication data on purpose to test recovery mechanisms."""

    @abc.abstractmethod
    def DisconnectBoard(
        self,
        request: flight_stand_api_v1_pb2.DisconnectBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.DisconnectBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.DisconnectBoardResponse]]:
        """Manually disconnect a board. Closes the board connection and releases resources (eg. COM port)."""

    @abc.abstractmethod
    def CreateSimulatedBoard(
        self,
        request: flight_stand_api_v1_pb2.CreateSimulatedBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.CreateSimulatedBoardResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.CreateSimulatedBoardResponse]]:
        """Add a simulated boards with virtual hardware. At this time, the simulated board cannot be customized. It simulates
        a small motor/propeller setup generating near 200 grams of thrust at full throttle.
        """

    @abc.abstractmethod
    def GetSimulatedBoardSettings(
        self,
        request: flight_stand_api_v1_pb2.GetSimulatedBoardSettingsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.SimulatedBoardSettings, collections.abc.Awaitable[flight_stand_api_v1_pb2.SimulatedBoardSettings]]:
        """Simulated boards can have some of its simulated properties changed after they have been created. For example, the
        user can add simulated correction weights to offset the simulated rotor unbalance.
        """

    @abc.abstractmethod
    def UpdateSimulatedBoardSettings(
        self,
        request: flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.UpdateSimulatedBoardSettingsResponse]]: ...

    @abc.abstractmethod
    def CreateExternalBoard(
        self,
        request: flight_stand_api_v1_pb2.CreateExternalBoardRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Board, collections.abc.Awaitable[flight_stand_api_v1_pb2.Board]]:
        """Note: this feature requires a free license key. Contact support@tytorobotics.com to obtain one.
        Add an external board that fully interacts with the Flight Stand Software. This enables the user to interface
        external inputs and outputs, essentially allowing the control of CANbus ESCs and to add custom sensors and outputs.
        Once an external board is created, use the WriteExternalSamples rpc to update external sensor data, and use the
        WatchOutputs rpc to react to changes on the output targets. When reacting to changes on the output targets, you
        must take into account the rate limiter imposed by the user, Provide feedback the output reacted through the
        WriteExternalSamples rpc. See examples in the Python documentation for more information.
        """

    @abc.abstractmethod
    def FlashBoardFirmware(
        self,
        request: flight_stand_api_v1_pb2.FlashBoardFirmwareRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.FlashBoardFirmwareResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.FlashBoardFirmwareResponse]]:
        """Flashes the firmware on a board. The core has the correct supported firmware in its source already. The core will
        handle all the logic to reset, disconnect, flash, reconnect, etc...
        """

    @abc.abstractmethod
    def GetInput(
        self,
        request: flight_stand_api_v1_pb2.GetInputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Input, collections.abc.Awaitable[flight_stand_api_v1_pb2.Input]]:
        """Gets an input"""

    @abc.abstractmethod
    def UpdateInput(
        self,
        request: flight_stand_api_v1_pb2.UpdateInputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Input, collections.abc.Awaitable[flight_stand_api_v1_pb2.Input]]:
        """Updates an input"""

    @abc.abstractmethod
    def ListInputs(
        self,
        request: flight_stand_api_v1_pb2.ListInputsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListInputsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListInputsResponse]]:
        """Lists available inputs. Does not return closed inputs"""

    @abc.abstractmethod
    def WatchInputs(
        self,
        request: flight_stand_api_v1_pb2.WatchInputsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Input], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Input]]:
        """Watches inputs for changes (other than the values). When first called, each available input is streamed once."""

    @abc.abstractmethod
    def TareInputs(
        self,
        request: flight_stand_api_v1_pb2.TareInputsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TareInputsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.TareInputsResponse]]:
        """Tares all inputs on all boards that can be tared, for example load cells."""

    @abc.abstractmethod
    def ListSamples(
        self,
        request: flight_stand_api_v1_pb2.ListSamplesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListSamplesResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListSamplesResponse]]:
        """Returns the latest Sample values."""

    @abc.abstractmethod
    def WatchSamples(
        self,
        request_iterator: _MaybeAsyncIterator[flight_stand_api_v1_pb2.WatchSamplesRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.WatchSamplesResponse], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.WatchSamplesResponse]]:
        """Regularly get Sample updates. This RPC is designed to provide real-time updates for the Flight Stand GUI's plots.
        Unlike polling with ListSamples, this method uses an internal buffer that accumulates updates (up to a reasonable
        limit) when the client temporarily slows down, ensuring that the client won't miss any updates. This is especially
        useful when the GUI freezes occasionally due to actions like docking or undocking windows. The network stream is
        also buffered, and a response is sent only when a request is received to prevent lag. It's important to note that
        this RPC has been heavily optimized for use with the Flight Stand GUI. The sample rate is fixed at 10 Hz and
        cannot be configured. The RPC has been crafted and optimized to provide smooth real-time plots in the GUI while
        keeping RAM and CPU usage within reasonable limits. To prevent the send buffer from filling up, the RPC employs
        techniques similar to those used in real-time video conferencing. The idea is to limit latency by limiting the
        amount of buffering that can be done. To achieve this, the client must acknowledge receipt of the data before the
        RPC will send more data. In summary, it's required to use this RPC as a bidirectional stream, as it expects the GUI
        to respond after each update.
        """

    @abc.abstractmethod
    def WriteExternalSamples(
        self,
        request: flight_stand_api_v1_pb2.WriteExternalSamplesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.WriteExternalSamplesResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.WriteExternalSamplesResponse]]:
        """Writes external input samples. This rpc only works on external inputs added using the CreateExternalBoard rpc.
        When creating the Sample, assign the input's raw_signal_name field to the Sample's signal_name field.
        """

    @abc.abstractmethod
    def GetSignal(
        self,
        request: flight_stand_api_v1_pb2.GetSignalRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Signal, collections.abc.Awaitable[flight_stand_api_v1_pb2.Signal]]:
        """Gets a signal. See the "Signal" message for more information about what a signal represents."""

    @abc.abstractmethod
    def ListSignals(
        self,
        request: flight_stand_api_v1_pb2.ListSignalsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListSignalsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListSignalsResponse]]:
        """List all signals."""

    @abc.abstractmethod
    def WatchSignals(
        self,
        request: flight_stand_api_v1_pb2.WatchSignalsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Signal], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Signal]]:
        """Watch signals for changes. When first called, all signals are streamed once."""

    @abc.abstractmethod
    def ListSignalStats(
        self,
        request: flight_stand_api_v1_pb2.ListSignalStatsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListSignalStatsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListSignalStatsResponse]]:
        """List signal stats. Gets signal performance metrics, like update rate."""

    @abc.abstractmethod
    def GetOutput(
        self,
        request: flight_stand_api_v1_pb2.GetOutputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Output, collections.abc.Awaitable[flight_stand_api_v1_pb2.Output]]:
        """Get an output's configuration (cutoff, range, alias, protocol, etc...)."""

    @abc.abstractmethod
    def UpdateOutput(
        self,
        request: flight_stand_api_v1_pb2.UpdateOutputRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Output, collections.abc.Awaitable[flight_stand_api_v1_pb2.Output]]:
        """Update an output's configuration or target value."""

    @abc.abstractmethod
    def ListOutputs(
        self,
        request: flight_stand_api_v1_pb2.ListOutputsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListOutputsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListOutputsResponse]]:
        """List all outputs. Does not return closed outputs."""

    @abc.abstractmethod
    def WatchOutputs(
        self,
        request: flight_stand_api_v1_pb2.WatchOutputsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Output], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Output]]:
        """Watch outputs for changes of configuration, other than OutputSignal changes."""

    @abc.abstractmethod
    def UpdateTimedActionSequence(
        self,
        request: flight_stand_api_v1_pb2.UpdateTimedActionSequenceRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TimedActionSequence, collections.abc.Awaitable[flight_stand_api_v1_pb2.TimedActionSequence]]:
        """Updates the action sequence (appends to previous sequence). This feature is related to automatic control. It allows
        controlling outputs in real-time at up to 1000 hz by specifying the update time. Compared to updating outputs
        directly using the UpdateOutput method, this method avoids issues with network/USB communication latency and
        limited rate of updates. Using this method ensures the outputs are updated at the correct time within the hardware.
        """

    @abc.abstractmethod
    def ClearTimedActionSequence(
        self,
        request: flight_stand_api_v1_pb2.ClearTimedActionSequenceRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ClearTimedActionSequenceResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ClearTimedActionSequenceResponse]]:
        """Clears the action sequence across all devices. This will prevent future updates from happening."""

    @abc.abstractmethod
    def GetPowertrain(
        self,
        request: flight_stand_api_v1_pb2.GetPowertrainRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Powertrain, collections.abc.Awaitable[flight_stand_api_v1_pb2.Powertrain]]:
        """Gets a powertrain. A powertrain represents a combination of a motor, a propeller, and an ESC. Each powertrain
        should be mapped with corresponding hardware sensors and outputs. The core will automatically calculate derived
        signals when possible. For example, if both a current and a voltage sensors are mapped, an "electrical power" is
        derived signal is generated.
        """

    @abc.abstractmethod
    def UpdatePowertrain(
        self,
        request: flight_stand_api_v1_pb2.UpdatePowertrainRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Powertrain, collections.abc.Awaitable[flight_stand_api_v1_pb2.Powertrain]]:
        """Updates a powertrain."""

    @abc.abstractmethod
    def ListPowertrains(
        self,
        request: flight_stand_api_v1_pb2.ListPowertrainsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListPowertrainsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListPowertrainsResponse]]:
        """Lists all powertrains."""

    @abc.abstractmethod
    def ClearPowertrain(
        self,
        request: flight_stand_api_v1_pb2.ClearPowertrainRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ClearPowertrainResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ClearPowertrainResponse]]:
        """Clear a powertrain (removes every mapping and component names)."""

    @abc.abstractmethod
    def WatchPowertrains(
        self,
        request: flight_stand_api_v1_pb2.WatchPowertrainsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.Powertrain], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.Powertrain]]:
        """Watch changes on powertrains."""

    @abc.abstractmethod
    def GetTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.GetTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TestRecorder, collections.abc.Awaitable[flight_stand_api_v1_pb2.TestRecorder]]:
        """Gets the test recorder, used to prepare a test before saving."""

    @abc.abstractmethod
    def UpdateTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.UpdateTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TestRecorder, collections.abc.Awaitable[flight_stand_api_v1_pb2.TestRecorder]]:
        """Updates the test recorder."""

    @abc.abstractmethod
    def WatchTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.WatchTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.TestRecorder], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.TestRecorder]]:
        """Watch the test recorder for changes."""

    @abc.abstractmethod
    def TakeSampleTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.TakeSampleTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.TakeSampleTestRecorderResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.TakeSampleTestRecorderResponse]]:
        """Take a data sample."""

    @abc.abstractmethod
    def ClearTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.ClearTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ClearTestRecorderResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ClearTestRecorderResponse]]:
        """Discard changes and start a new test recorder."""

    @abc.abstractmethod
    def SaveTestRecorder(
        self,
        request: flight_stand_api_v1_pb2.SaveTestRecorderRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.SaveTestRecorderResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.SaveTestRecorderResponse]]:
        """Save the test recorder as a new Test."""

    @abc.abstractmethod
    def GetTest(
        self,
        request: flight_stand_api_v1_pb2.GetTestRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Test, collections.abc.Awaitable[flight_stand_api_v1_pb2.Test]]:
        """Gets a Test."""

    @abc.abstractmethod
    def UpdateTest(
        self,
        request: flight_stand_api_v1_pb2.UpdateTestRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.Test, collections.abc.Awaitable[flight_stand_api_v1_pb2.Test]]:
        """Update a Test."""

    @abc.abstractmethod
    def ListTests(
        self,
        request: flight_stand_api_v1_pb2.ListTestsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListTestsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListTestsResponse]]:
        """List all tests."""

    @abc.abstractmethod
    def DeleteTest(
        self,
        request: flight_stand_api_v1_pb2.DeleteTestRequest,
        context: _ServicerContext,
    ) -> typing.Union[google.protobuf.empty_pb2.Empty, collections.abc.Awaitable[google.protobuf.empty_pb2.Empty]]:
        """Delete a test."""

    @abc.abstractmethod
    def ListTestData(
        self,
        request: flight_stand_api_v1_pb2.ListTestSamplesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListTestSamplesResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListTestSamplesResponse]]:
        """Retrieve the recorded data for a test (may be interpolated to reduce the amount of data). The data is returned with
        timestamps in order. The deadline specified in the context of the API call will force an early return even if the
        length of the returned data has not reached pageSize. This is useful to display progress bars.
        """

    @abc.abstractmethod
    def DevListBoardParameters(
        self,
        request: flight_stand_api_v1_pb2.DevListBoardParametersRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.DevListBoardParametersResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.DevListBoardParametersResponse]]:
        """Lists all board parameters. This function is synchronous, and will return after fetching all board parameters from
        the board. Important: for dev purposes ONLY (it bypasses all safety and business logic). Calling this function may
        also have unexpected behavior (may trigger an internal cutoff, stop data streaming, or load default values).
        """

    @abc.abstractmethod
    def DevUpdateBoardParameter(
        self,
        request: flight_stand_api_v1_pb2.DevUpdateBoardParameterRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.BoardParameter, collections.abc.Awaitable[flight_stand_api_v1_pb2.BoardParameter]]:
        """Updates a board parameter. For simplicity this update method does not use field masks, so the whole parameter
        must be specified when updating. For dev purposes ONLY (it bypasses all safety and business logic). There is no
        defined behavior on the effect of updating a parameter (changes are not expected to propagate, a board reset may be
        needed for changes to take effect).
        """

    @abc.abstractmethod
    def DevClearBoardParameters(
        self,
        request: flight_stand_api_v1_pb2.DevClearBoardParametersRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.DevClearBoardParametersResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.DevClearBoardParametersResponse]]:
        """Clears all parameters to 0 value. It is recommended to leave a timeout of 30 seconds for this command to reply.
        For dev purposes ONLY. This will delete all calibration data, and the circuit will become unusable.
        """

    @abc.abstractmethod
    def ListInputTransformations(
        self,
        request: flight_stand_api_v1_pb2.ListInputTransformationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListInputTransformationsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListInputTransformationsResponse]]:
        """List existing InputTransformations"""

    @abc.abstractmethod
    def UpdateInputTransformations(
        self,
        request: flight_stand_api_v1_pb2.UpdateInputTransformationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.UpdateInputTransformationsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.UpdateInputTransformationsResponse]]:
        """Updates the list of input transformations. The order of the transformations is important when chaining them."""

    @abc.abstractmethod
    def WatchInputTransformations(
        self,
        request: flight_stand_api_v1_pb2.WatchInputTransformationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[flight_stand_api_v1_pb2.WatchInputTransformationsResponse], collections.abc.AsyncIterator[flight_stand_api_v1_pb2.WatchInputTransformationsResponse]]:
        """Watch input transformations. When first called, it sends the current list of input transformations. Each time there
        is an update, all inputs transformations are resent because their order is important.
        """

    @abc.abstractmethod
    def LoadTransformationFromID(
        self,
        request: flight_stand_api_v1_pb2.LoadTransformationFromIDRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.LoadTransformationFromIDResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.LoadTransformationFromIDResponse]]:
        """Load Tyto Robotics transformation. For sensors sold and calibrated by Tyto Robotics, the transformation associated
        with the sensor can be loaded by entering the calibration ID found in the product's label. It will show as a new
        transformation.
        """

    @abc.abstractmethod
    def ListBalancingSessions(
        self,
        request: flight_stand_api_v1_pb2.ListBalancingSessionsRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListBalancingSessionsResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListBalancingSessionsResponse]]:
        """Lists available balancing sessions."""

    @abc.abstractmethod
    def DeleteBalancingSession(
        self,
        request: flight_stand_api_v1_pb2.DeleteBalancingSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[google.protobuf.empty_pb2.Empty, collections.abc.Awaitable[google.protobuf.empty_pb2.Empty]]:
        """Delete a balance session."""

    @abc.abstractmethod
    def CreateBalancingSession(
        self,
        request: flight_stand_api_v1_pb2.CreateBalancingSessionRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.CreateBalancingSessionResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.CreateBalancingSessionResponse]]:
        """Creates a new balancing session. The new session can only be modified if the system state matches the system's
        snapshot state when the session is created and if the session is the last in the list of sessions.
        """

    @abc.abstractmethod
    def ExecuteBalancingRun(
        self,
        request: flight_stand_api_v1_pb2.ExecuteBalancingRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ExecuteBalancingRunResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ExecuteBalancingRunResponse]]:
        """Synchronous function that captures and analyzes a run of data and appends it to the last balancing session.
        Add trial or correction weight. By definition a trial weight is the first weight added for the trial run, while
        correction weights are applied to correct the balance in one or more correction runs.
        The first run is done without any correction weight, and is called the initial run.
        The second run has a trial weight and is called a trial run. This is where Wa and WT are determined.
        Subsequent runs are called correction runs and there can be one or more.
        """

    @abc.abstractmethod
    def ListBalanceRunData(
        self,
        request: flight_stand_api_v1_pb2.ListBalanceRunDataRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.ListBalanceRunDataResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.ListBalanceRunDataResponse]]:
        """Retrieves the recorded data points for a balancing run"""

    @abc.abstractmethod
    def GetOhmValue(
        self,
        request: flight_stand_api_v1_pb2.GetOhmValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[flight_stand_api_v1_pb2.GetOhmValueResponse, collections.abc.Awaitable[flight_stand_api_v1_pb2.GetOhmValueResponse]]:
        """Gets ohmic resistance of the motor windings."""

def add_FlightStandServicer_to_server(servicer: FlightStandServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
